### ISSUE TITLE
Feature Request: CORS headers

### ISSUE THREAD

**Issue by robinbaxon** [itzg/mc-status#1]
Hi, thanks for the great work on mc-status. I really like your all-in-one-jar. It really does exactly what I was looking for.

One thing that I would love is the option to set the CORS headers (e.g. Access-Control-Allow-Origin) via a switch(--access-control-allow-origin=my.domain.com, or a list of separated domains). 

This would make the API  consumable from a http client respecting CORS policies (all modern browsers).  E.g. a client originating from my.minecraft.domain.com could consume the-minecraft.server:8080/server without violating CORS policies (and in the case of Chrome,FF,ie: not allowing the response to be consumed). Thanks again for a great status thingie!

**Comment by itzg** [comment]
I can definitely fix that. In fact, I'm thinking I should just disable CORS by default since this is an API server.

**Comment by itzg** [comment]
...ok, now I see what you mean. CORS is "disabled", but as you said that's actually a problem for CORS-enforcing clients. Still very fixable :)

**Comment by robinbaxon** [comment]
Quick response :-) Yes, that's right. If I want to tell all CORS-enforcing clients that "you're free to consume my data", I would need the option of setting Access-Control-Allow-Origin to * .

**Comment by itzg** [comment]
For my notes, here's what an error looks like:
```
Failed to load http://localhost:8080/servers: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by itzg** [comment]
I have published a new version that adds the `--cors.allowOrigins` option (documented in [README](https://github.com/itzg/mc-status#usage-as-a-rest-server)). I also defaulted it to allow "*" since that's more useful being a REST-only server.

**Comment by robinbaxon** [comment]
Thanks a bunch, @itzg  :-) Have yourself a very happy tuesday.
